services:
  # Admin Dashboard Service
  - type: web
    name: bsm-admin-dashboard
    env: node
    plan: starter
    buildCommand: npm install && npm run build:admin
    startCommand: npm run start:admin
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_SUPABASE_URL
        value: https://zrxoiqhivfkgzvyoobki.supabase.co
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        value: your_actual_supabase_anon_key_here
      - key: NEXT_PUBLIC_APP_URL
        value: https://bsm-admin-dashboard.onrender.com
    healthCheckPath: /welcome
    autoDeploy: true

  # Customer Portal Service
  - type: web
    name: bsm-customer-portal
    env: node
    plan: starter
    buildCommand: npm install && npm run build:customer
    startCommand: npm run start:customer
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_SUPABASE_URL
        value: https://zrxoiqhivfkgzvyoobki.supabase.co
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        value: your_actual_supabase_anon_key_here
      - key: NEXT_PUBLIC_APP_URL
        value: https://bsm-customer-portal.onrender.com
    healthCheckPath: /
    autoDeploy: true

  # Customer Portal 3002 Service
  - type: web
    name: bsm-customer-portal-3002
    env: node
    plan: starter
    buildCommand: npm install && npm run build:customer3002
    startCommand: npm run start:customer3002
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_SUPABASE_URL
        value: https://zrxoiqhivfkgzvyoobki.supabase.co
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        value: your_actual_supabase_anon_key_here
      - key: NEXT_PUBLIC_APP_URL
        value: https://bsm-customer-portal-3002.onrender.com
    healthCheckPath: /
    autoDeploy: true

